FROM registry.access.redhat.com/ubi8/ubi-minimal
WORKDIR /work/

ARG NATIVE_EXECUTABLE=quarkus-showcase-runner
COPY target/${NATIVE_EXECUTABLE} /work/application
RUN chmod 775 /work

EXPOSE 8080
CMD ["./application", "-Dquarkus.http.host=0.0.0.0"]