DROP TABLE IF EXISTS public.GREETING;
CREATE TABLE public.GREETING (
    ID BIGINT NOT NULL PRIMARY KEY,
    SALUTATION VARCHAR(64) NOT NULL,
    RESPONSE VARCHAR(64) NOT NULL
    );

INSERT INTO public.GREETING (ID, SALUTATION, RESPONSE) VALUES (1, 'Marco', 'Polo');
INSERT INTO public.GREETING (ID, SALUTATION, RESPONSE) VALUES (2, 'Ping', 'Pong');
INSERT INTO public.GREETING (ID, SALUTATION, RESPONSE) VALUES (3, 'Moin', 'Moin');